name: CI - Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install DVC
      run: |
        pip install dvc[s3]

    - name: Configure DVC remote
      run: |
        dvc remote add -d myremote ${{ secrets.BACKBLAZE_SECRET_FOLDER_PATH }}
        dvc remote modify myremote access_key_id ${{ secrets.BACKBLAZE_ACCESS_KEY_ID }}
        dvc remote modify myremote secret_access_key ${{ secrets.BACKBLAZE_SECRET_ACCESS_KEY }}
        dvc remote modify myremote endpointurl ${{ secrets.BACKBLAZE_SECRET_ENDPOINT }}

    - name: Pull DVC files
      run: |
        dvc pull models/best_v4.pt.dvc
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.BACKBLAZE_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKBLAZE_SECRET_ACCESS_KEY }}


    - name: Set up Docker Buildx  
      uses: docker/setup-buildx-action@v2

    - name: Build backend image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: my-app/backend:latest

    - name: Build frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false # We are only building, not pushing
        tags: my-app/frontend:latest