name: CI - Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install DVC
      run: |
        pip install dvc[s3]

    - name: Configure DVC remote
      run: |
        dvc remote add -d myremote ${{ secrets.BACKBLAZE_SECRET_FOLDER_PATH }}
        dvc remote modify myremote access_key_id ${{ secrets.BACKBLAZE_ACCESS_KEY_ID }}
        dvc remote modify myremote secret_access_key ${{ secrets.BACKBLAZE_SECRET_ACCESS_KEY }}
        dvc remote modify myremote endpointurl ${{ secrets.BACKBLAZE_SECRET_ENDPOINT }}

    - name: Pull DVC files
      run: |
        dvc pull models/best_v4.pt.dvc
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.BACKBLAZE_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKBLAZE_SECRET_ACCESS_KEY }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx  
      uses: docker/setup-buildx-action@v2

    - name: Generate image tags
      id: meta
      run: |
        echo "BACKEND_TAG=${{ secrets.DOCKERHUB_USERNAME }}/my-app-backend:${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "FRONTEND_TAG=${{ secrets.DOCKERHUB_USERNAME }}/my-app-frontend:${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "BACKEND_LATEST=${{ secrets.DOCKERHUB_USERNAME }}/my-app-backend:latest" >> $GITHUB_OUTPUT
        echo "FRONTEND_LATEST=${{ secrets.DOCKERHUB_USERNAME }}/my-app-frontend:latest" >> $GITHUB_OUTPUT

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ steps.meta.outputs.BACKEND_TAG }}
          ${{ steps.meta.outputs.BACKEND_LATEST }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ steps.meta.outputs.FRONTEND_TAG }}
          ${{ steps.meta.outputs.FRONTEND_LATEST }}

    # Output the image URLs for easy reference
    - name: Output image information
      run: |
        echo "Backend image: ${{ steps.meta.outputs.BACKEND_LATEST }}"
        echo "Frontend image: ${{ steps.meta.outputs.FRONTEND_LATEST }}"
        echo "Backend SHA tag: ${{ steps.meta.outputs.BACKEND_TAG }}"
        echo "Frontend SHA tag: ${{ steps.meta.outputs.FRONTEND_TAG }}"